# Generated by Django 5.0.1 on 2024-01-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0004_nippomodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nippomodel',
            name='user',
        ),
    ]
