# Generated by Django 5.0.1 on 2024-01-23 13:41

import nippo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0008_nippomodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nippomodel',
            name='slug',
            field=models.SlugField(default=nippo.models.slug_maker, max_length=20, unique=True),
        ),
    ]
