# Generated by Django 5.0.1 on 2024-01-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nippo', '0010_nippomodel_datte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nippomodel',
            old_name='datte',
            new_name='date',
        ),
    ]
